server.port: 7002

spring.data.mongodb:
  host: localhost
  port: 27017
  database: recommendation-db

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: recommendations
    group: recommendationsGroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

spring:
  data:
    mongodb:
      host: localhost
      port: 27017

logging:
  level:
    root: INFO
    se.magnus: DEBUG
---
spring:
  data:
    mongodb:
      host: mongodb
  profiles:
    - docker
server:
  port: 80

---
spring.profiles: prod

spring.data.mongodb.host: 172.17.0.1

logging:
  level:
    root: WARN
    se.magnus: WARN
    org.springframework.data.mongodb.core.MongoTemplate: WARN