version: '2.1'

services:
  product:
    build: microservices/product
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  
  recommendation:
    build: microservices/recommendation
    mem_limit: 350m
    environment: 
     - SPRING_PROFILES_ACTIVE=docker
  
  review:
    build: microservices/review
    mem_limit: 350m
    environment:
     - SPRING_PROFILES_ACTIVE=docker

  product-composite:
    build: microservices/composite.product
    mem_limit: 350m
    ports:
     - 8080:8080
    environment:
     - SPRING_PROFILES_ACTIVE=docker