version: '2.1'

services:
  rabbitmq:
    image: rabbitmq:3.7.8-management
    mem_limit: 350m
    ports:
    - 5672:5672
    - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo:3.6.9
    mem_limit: 350m
    ports:
    - "27017:27017"
    command: mongod --smallfiles
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 10s
      timeout: 5s
      retries: 10

  mysql:
    image: mysql:5.7
    mem_limit: 350m
    ports:
    - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uuser", "-ppwd", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  product:
    build: microservices/product
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  
  recommendation:
    build: microservices/recommendation
    mem_limit: 350m
    environment: 
     - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  
  review:
    build: microservices/review
    mem_limit: 350m
    environment:
     - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy

  product-composite:
    build: microservices/composite.product
    mem_limit: 350m
    environment:
     - SPRING_PROFILES_ACTIVE=docker

  eureka:
    build: spring-cloud/eureka-server
    mem_limit: 350m

  gateway:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_SSL_KEY_STORE=file:/keystore/edgetest.p12
      - SERVER_SSL_KEY_STORE_PASSWORD=megatron
    volumes:
      - /home/projeto/Documentos/repositorios/estudoNew/microservices/keystore:/keystore
    build: spring-cloud/gateway
    mem_limit: 350m
    ports:
    - 8443:8443