

spring:
  data:
    mongodb:
      host: localhost
      port: 27017

server:
  port: 7001

logging:
  level:
    root: INFO
    br.com.microservices.core.product: DEBUG

management:
  endpoint:
    health:
      mongodb: false

---
spring:
  profiles:
    - docker
server:
  port: 8080