apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort #acessivel externamente em uma porta dedicada, em cada nó no cluster
  selector: #utilizado para encontrar os pods disponíveis
    app: nginx-app
  ports: #qual porta os pods estaram acessíveis
    - targetPort: 80
      port: 80 #porta aonde as solicitações devem ser encaminhadas
      nodePort: 30080  #porta acessível externamente